<?php

declare(strict_types=1);

/**
 * @file
 * Functions to support theming in the IU Indianapolis Libraries theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function iui_libraries_preprocess_html(array &$variables): void {
  $variables['iui_libraries_page_template'] = theme_get_setting('iui_libraries_page_template');
}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function iui_libraries_preprocess_page(array &$variables): void {
  $variables['iui_libraries_page_template'] = theme_get_setting('iui_libraries_page_template');
}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function iui_libraries_preprocess_node(array &$variables): void {
    $variables['iui_libraries_page_template'] = theme_get_setting('iui_libraries_page_template');
}

function iui_libraries_form_system_theme_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id = NULL) {
  // Work-around for a core bug affecting admin themes. See issue #943212.
  if (isset($form_id)) {
    return;
  }

  $form['iui_libraries_page_template'] = [
    '#type'          => 'select',
    '#title'         => t('Template Option'),
    '#options'       => [
        'default' => 'Default page template', 
        'alternate' => 'Alternate page template'
    ],
    '#default_value' => theme_get_setting('iui_libraries_page_template'),
    '#description'   => t('Place this text in the widget spot on your site.'),
  ];
}